// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/api": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "新增api",
                "parameters": [
                    {
                        "description": "api資訊",
                        "name": "api",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.AddApiRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/api/page": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "根據頁數獲取所有api",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "頁數",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每頁幾筆",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "路徑",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分組",
                        "name": "group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "請求",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_ApiItem"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/api/tree": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "獲取api tree",
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.ApiTree"
                                            }
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/api/{id}": {
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "編輯api",
                "parameters": [
                    {
                        "description": "api資訊",
                        "name": "api",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.EditApiRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "api id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "刪除api",
                "parameters": [
                    {
                        "type": "string",
                        "description": "api id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/cache/db": {
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "緩存"
                ],
                "summary": "清除資料庫緩存",
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系統"
                ],
                "summary": "登入",
                "parameters": [
                    {
                        "description": "帳號\u0026密碼",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.LoginResponse"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/logout": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系統"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/menu": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目錄"
                ],
                "summary": "獲取所有目錄",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜單名稱",
                        "name": "menuName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "true or false",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_MenuItem"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目錄"
                ],
                "summary": "新增菜單",
                "parameters": [
                    {
                        "description": "菜單",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.AddMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/menu/tree": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目錄"
                ],
                "summary": "獲取所有菜單tree",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "是否只查詢目錄",
                        "name": "dir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/menu/{id}": {
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目錄"
                ],
                "summary": "更新菜單",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜單ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "目錄",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.EditMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目錄"
                ],
                "summary": "刪除菜單",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜單ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系統"
                ],
                "summary": "註冊",
                "parameters": [
                    {
                        "description": "使用者資訊",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/role": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "獲取所有角色",
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.RoleItem"
                                            }
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "description": "角色資訊",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.AddRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/role/page": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "根據頁數獲取所有角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "頁數",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每頁幾筆",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色名稱",
                        "name": "roleName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ture or false",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_RoleItem"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/role/{role}": {
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色資訊",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.EditRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "刪除角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色",
                        "name": "role",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/role/{role}/status": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "設定狀態",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "設定",
                        "name": "in",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.SetStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "新增使用者",
                "parameters": [
                    {
                        "description": "使用者",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.AddUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/check/username": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "確認使用者是否存在",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者名稱",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/me": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "獲取使用者資訊",
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.UserInfoResponse"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/me/perm": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "獲取自身按鈕權限",
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/me/route": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "獲取自身menu",
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.RouteResponse"
                                            }
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/page": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "根據page, pageSize獲取使用者列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "頁數",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每頁幾筆",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "使用者名稱",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "暱稱",
                        "name": "nickName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_UserItem"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/password": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "修改密碼",
                "parameters": [
                    {
                        "description": "舊密碼\u0026新密碼",
                        "name": "Password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.ChangePassRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.UserInfoResponse"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "獲取使用者資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.UserInfoResponse"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "編輯使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "刪除使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/{id}/roles": {
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色",
                        "name": "roles",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.RolesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/user/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "更新使用者狀態",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "狀態",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.SetUserStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Ghostbb-io_g-api_app_system_model.AddApiRequest": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.AddMenuRequest": {
            "type": "object",
            "properties": {
                "affix": {
                    "description": "是否固定標簽",
                    "type": "boolean"
                },
                "carryParam": {
                    "description": "如果該路由會攜帶參數，且需要在tab頁上面顯示。則需要設置為true",
                    "type": "boolean"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.MenuItem"
                    }
                },
                "component": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentActiveMenu": {
                    "description": "當前激活的菜單。用於配置詳情頁時左側激活的菜單路徑",
                    "type": "string"
                },
                "dynamicLevel": {
                    "description": "動態路由可打開Tab頁數",
                    "type": "integer"
                },
                "frameSrc": {
                    "description": "內嵌iframe的地址",
                    "type": "string"
                },
                "hideBreadcrumb": {
                    "description": "隱藏該路由在面包屑上面的顯示",
                    "type": "boolean"
                },
                "hideChildrenInMenu": {
                    "description": "隱藏所有子菜單",
                    "type": "boolean"
                },
                "hideMenu": {
                    "description": "當前路由不再菜單顯示",
                    "type": "boolean"
                },
                "hidePathForChildren": {
                    "description": "是否在子級菜單的完整path中忽略本級path。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "hideTab": {
                    "description": "當前路由不再標簽頁顯示",
                    "type": "boolean"
                },
                "icon": {
                    "description": "圖標，也是菜單圖標",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ignoreKeepAlive": {
                    "description": "是否忽略KeepAlive緩存",
                    "type": "boolean"
                },
                "ignoreRoute": {
                    "description": "忽略路由。用於在ROUTE_MAPPING以及BACK權限模式下，生成對應的菜單而忽略路由。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "realPath": {
                    "description": "動態路由的實際Path, 即去除路由的動態部分;",
                    "type": "string"
                },
                "redirect": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "title": {
                    "description": "路由title  一般必填",
                    "type": "string"
                },
                "transitionName": {
                    "description": "指定該路由切換的動畫名",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.AddRoleRequest": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "menu": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.AddUserRequest": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mobile": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.ApiItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.ApiTree": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.ApiTree"
                    }
                },
                "key": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_ApiItem": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.ApiItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_MenuItem": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.MenuItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_RoleItem": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.RoleItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.BasicFetchResult-github_com_Ghostbb-io_g-api_app_system_model_UserItem": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.UserItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.ChangePassRequest": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.EditApiRequest": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.EditMenuRequest": {
            "type": "object",
            "properties": {
                "affix": {
                    "description": "是否固定標簽",
                    "type": "boolean"
                },
                "carryParam": {
                    "description": "如果該路由會攜帶參數，且需要在tab頁上面顯示。則需要設置為true",
                    "type": "boolean"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.MenuItem"
                    }
                },
                "component": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentActiveMenu": {
                    "description": "當前激活的菜單。用於配置詳情頁時左側激活的菜單路徑",
                    "type": "string"
                },
                "dynamicLevel": {
                    "description": "動態路由可打開Tab頁數",
                    "type": "integer"
                },
                "frameSrc": {
                    "description": "內嵌iframe的地址",
                    "type": "string"
                },
                "hideBreadcrumb": {
                    "description": "隱藏該路由在面包屑上面的顯示",
                    "type": "boolean"
                },
                "hideChildrenInMenu": {
                    "description": "隱藏所有子菜單",
                    "type": "boolean"
                },
                "hideMenu": {
                    "description": "當前路由不再菜單顯示",
                    "type": "boolean"
                },
                "hidePathForChildren": {
                    "description": "是否在子級菜單的完整path中忽略本級path。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "hideTab": {
                    "description": "當前路由不再標簽頁顯示",
                    "type": "boolean"
                },
                "icon": {
                    "description": "圖標，也是菜單圖標",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ignoreKeepAlive": {
                    "description": "是否忽略KeepAlive緩存",
                    "type": "boolean"
                },
                "ignoreRoute": {
                    "description": "忽略路由。用於在ROUTE_MAPPING以及BACK權限模式下，生成對應的菜單而忽略路由。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "realPath": {
                    "description": "動態路由的實際Path, 即去除路由的動態部分;",
                    "type": "string"
                },
                "redirect": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "title": {
                    "description": "路由title  一般必填",
                    "type": "string"
                },
                "transitionName": {
                    "description": "指定該路由切換的動畫名",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.EditRoleRequest": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "menu": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.MenuItem": {
            "type": "object",
            "properties": {
                "affix": {
                    "description": "是否固定標簽",
                    "type": "boolean"
                },
                "carryParam": {
                    "description": "如果該路由會攜帶參數，且需要在tab頁上面顯示。則需要設置為true",
                    "type": "boolean"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.MenuItem"
                    }
                },
                "component": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentActiveMenu": {
                    "description": "當前激活的菜單。用於配置詳情頁時左側激活的菜單路徑",
                    "type": "string"
                },
                "dynamicLevel": {
                    "description": "動態路由可打開Tab頁數",
                    "type": "integer"
                },
                "frameSrc": {
                    "description": "內嵌iframe的地址",
                    "type": "string"
                },
                "hideBreadcrumb": {
                    "description": "隱藏該路由在面包屑上面的顯示",
                    "type": "boolean"
                },
                "hideChildrenInMenu": {
                    "description": "隱藏所有子菜單",
                    "type": "boolean"
                },
                "hideMenu": {
                    "description": "當前路由不再菜單顯示",
                    "type": "boolean"
                },
                "hidePathForChildren": {
                    "description": "是否在子級菜單的完整path中忽略本級path。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "hideTab": {
                    "description": "當前路由不再標簽頁顯示",
                    "type": "boolean"
                },
                "icon": {
                    "description": "圖標，也是菜單圖標",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ignoreKeepAlive": {
                    "description": "是否忽略KeepAlive緩存",
                    "type": "boolean"
                },
                "ignoreRoute": {
                    "description": "忽略路由。用於在ROUTE_MAPPING以及BACK權限模式下，生成對應的菜單而忽略路由。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "realPath": {
                    "description": "動態路由的實際Path, 即去除路由的動態部分;",
                    "type": "string"
                },
                "redirect": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "title": {
                    "description": "路由title  一般必填",
                    "type": "string"
                },
                "transitionName": {
                    "description": "指定該路由切換的動畫名",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.RoleInfo": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.RoleItem": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "menu": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.RolesRequest": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.RouteResponse": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.RouteResponse"
                    }
                },
                "component": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model_table.Meta"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "redirect": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.SetStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.SetUserStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.UserInfoResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ghostbb-io_g-api_app_system_model.RoleInfo"
                    }
                },
                "userId": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model.UserItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mobile": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_app_system_model_table.Meta": {
            "type": "object",
            "properties": {
                "affix": {
                    "description": "是否固定標簽",
                    "type": "boolean"
                },
                "carryParam": {
                    "description": "如果該路由會攜帶參數，且需要在tab頁上面顯示。則需要設置為true",
                    "type": "boolean"
                },
                "currentActiveMenu": {
                    "description": "當前激活的菜單。用於配置詳情頁時左側激活的菜單路徑",
                    "type": "string"
                },
                "dynamicLevel": {
                    "description": "動態路由可打開Tab頁數",
                    "type": "integer"
                },
                "frameSrc": {
                    "description": "內嵌iframe的地址",
                    "type": "string"
                },
                "hideBreadcrumb": {
                    "description": "隱藏該路由在面包屑上面的顯示",
                    "type": "boolean"
                },
                "hideChildrenInMenu": {
                    "description": "隱藏所有子菜單",
                    "type": "boolean"
                },
                "hideMenu": {
                    "description": "當前路由不再菜單顯示",
                    "type": "boolean"
                },
                "hidePathForChildren": {
                    "description": "是否在子級菜單的完整path中忽略本級path。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "hideTab": {
                    "description": "當前路由不再標簽頁顯示",
                    "type": "boolean"
                },
                "icon": {
                    "description": "圖標，也是菜單圖標",
                    "type": "string"
                },
                "ignoreKeepAlive": {
                    "description": "是否忽略KeepAlive緩存",
                    "type": "boolean"
                },
                "ignoreRoute": {
                    "description": "忽略路由。用於在ROUTE_MAPPING以及BACK權限模式下，生成對應的菜單而忽略路由。2.5.3以上版本有效",
                    "type": "boolean"
                },
                "realPath": {
                    "description": "動態路由的實際Path, 即去除路由的動態部分;",
                    "type": "string"
                },
                "title": {
                    "description": "路由title  一般必填",
                    "type": "string"
                },
                "transitionName": {
                    "description": "指定該路由切換的動畫名",
                    "type": "string"
                }
            }
        },
        "github_com_Ghostbb-io_g-api_pkg_utils_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "g-api",
	Description:      "api框架",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
